[' - MARKET VALUE',' - DIVIDEND YIELD',' - EARNINGS PER SHR',' - PRICE HIGH',' - PRICE LOW',' - OPENING PRICE',' - TURNOVER BY VALUE',' - TURNOVER BY VOLUME',' - BK VAL PS 12M FWD',' - EV 12M FWD',' - NET INCOME 12M FWD',' - PRETAX PRF 12M FWD',' - ROE 12M FWD',' - SALES 12M FWD',' - P/CSH FLOW RATIO',' - PRICE TO BOOK VAL',' - NUMBER OF SHARES']
import numpy as np

def listofcolumn():
  return [2,3,26,33,34,36,39,40,49,50,51,52,53,54,60,61,65]
  
